### ISSUE TITLE
DB Schema Sketch

### ISSUE THREAD

**Issue by EkaterinaSerga** [CookStars/cookstarsapp#8]
- [x] database models completed
- [x] figure out how firebase works
- [x] set up firebase
- [x] pull recipes from API and seed the data
- [x] get data and manage state (watch for changes in database)

**Comment by ghost** [comment]
{
    "recipes": [
        {
            "vegetarian": true,
            "vegan": false,
            "glutenFree": false,
            "dairyFree": false,
            "veryHealthy": false,
            "cheap": false,
            "veryPopular": false,
            "sustainable": false,
            "weightWatcherSmartPoints": 14,
            "gaps": "no",
            "lowFodmap": false,
            "aggregateLikes": 36,
            "spoonacularScore": 27.0,
            "healthScore": 2.0,
            "creditsText": "Afrolems",
            "license": "CC BY 4.0",
            "sourceName": "Afrolems",
            "pricePerServing": 71.63,
            "extendedIngredients": [
                {
                    "id": 18371,
                    "aisle": "Baking",
                    "image": "white-powder.jpg",
                    "consistency": "solid",
                    "name": "baking powder",
                    "original": "1 teaspoon baking powder",
                    "originalString": "1 teaspoon baking powder",
                    "originalName": "baking powder",
                    "amount": 1.0,
                    "unit": "teaspoon",
                    "meta": [],
                    "metaInformation": [],
                    "measures": {
                        "us": {
                            "amount": 1.0,
                            "unitShort": "tsp",
                            "unitLong": "teaspoon"
                        },
                        "metric": {
                            "amount": 1.0,
                            "unitShort": "tsp",
                            "unitLong": "teaspoon"
                        }
                    }
                },
                {
                    "id": 1001,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "butter-sliced.jpg",
                    "consistency": "solid",
                    "name": "butter",
                    "original": "160 g of butter at room temperature",
                    "originalString": "160 g of butter at room temperature",
                    "originalName": "butter at room temperature",
                    "amount": 160.0,
                    "unit": "g",
                    "meta": [
                        "at room temperature"
                    ],
                    "metaInformation": [
                        "at room temperature"
                    ],
                    "measures": {
                        "us": {
                            "amount": 5.644,
                            "unitShort": "oz",
                            "unitLong": "ounces"
                        },
                        "metric": {
                            "amount": 160.0,
                            "unitShort": "g",
                            "unitLong": "grams"
                        }
                    }
                },
                {
                    "id": 1123,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "egg.png",
                    "consistency": "solid",
                    "name": "eggs",
                    "original": "5 large eggs at room temperature",
                    "originalString": "5 large eggs at room temperature",
                    "originalName": "eggs at room temperature",
                    "amount": 5.0,
                    "unit": "large",
                    "meta": [
                        "at room temperature"
                    ],
                    "metaInformation": [
                        "at room temperature"
                    ],
                    "measures": {
                        "us": {
                            "amount": 5.0,
                            "unitShort": "large",
                            "unitLong": "larges"
                        },
                        "metric": {
                            "amount": 5.0,
                            "unitShort": "large",
                            "unitLong": "larges"
                        }
                    }
                },
                {
                    "id": 1118,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "white-cream.png",
                    "consistency": "liquid",
                    "name": "fat free natural yogurt",
                    "original": "1/2 cup of natural yogurt (fat free preferable and removed from fridge at least 30 minutes before using)",
                    "originalString": "1/2 cup of natural yogurt (fat free preferable and removed from fridge at least 30 minutes before using)",
                    "originalName": "natural yogurt (fat free preferable and removed from fridge at least 30 minutes before using)",
                    "amount": 0.5,
                    "unit": "cup",
                    "meta": [
                        "fat free",
                        "( preferable and removed from fridge at least 30 minutes before using)"
                    ],
                    "metaInformation": [
                        "fat free",
                        "( preferable and removed from fridge at least 30 minutes before using)"
                    ],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "cups",
                            "unitLong": "cups"
                        },
                        "metric": {
                            "amount": 118.294,
                            "unitShort": "ml",
                            "unitLong": "milliliters"
                        }
                    }
                },
                {
                    "id": 19335,
                    "aisle": "Baking",
                    "image": "sugar-in-bowl.png",
                    "consistency": "solid",
                    "name": "granulated sugar",
                    "original": "1 cup of granulated sugar (you can use half cup if you don't like much sugar)",
                    "originalString": "1 cup of granulated sugar (you can use half cup if you don't like much sugar)",
                    "originalName": "granulated sugar (you can use half cup if you don't like much sugar)",
                    "amount": 1.0,
                    "unit": "cup",
                    "meta": [
                        "canned",
                        "(you can use half cup if you don't like much sugar)"
                    ],
                    "metaInformation": [
                        "canned",
                        "(you can use half cup if you don't like much sugar)"
                    ],
                    "measures": {
                        "us": {
                            "amount": 1.0,
                            "unitShort": "cup",
                            "unitLong": "cup"
                        },
                        "metric": {
                            "amount": 236.588,
                            "unitShort": "ml",
                            "unitLong": "milliliters"
                        }
                    }
                },
                {
                    "id": 1077,
                    "aisle": "Milk, Eggs, Other Dairy",
                    "image": "milk.png",
                    "consistency": "liquid",
                    "name": "milk",
                    "original": "1/4 cup of milk",
                    "originalString": "1/4 cup of milk",
                    "originalName": "milk",
                    "amount": 0.25,
                    "unit": "cup",
                    "meta": [],
                    "metaInformation": [],
                    "measures": {
                        "us": {
                            "amount": 0.25,
                            "unitShort": "cups",
                            "unitLong": "cups"
                        },
                        "metric": {
                            "amount": 59.147,
                            "unitShort": "ml",
                            "unitLong": "milliliters"
                        }
                    }
                },
                {
                    "id": 2025,
                    "aisle": "Spices and Seasonings",
                    "image": "ground-nutmeg.jpg",
                    "consistency": "solid",
                    "name": "nutmeg",
                    "original": "1 small nutmeg (1/2 teaspoon)",
                    "originalString": "1 small nutmeg (1/2 teaspoon)",
                    "originalName": "small nutmeg",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "metaInformation": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons"
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons"
                        }
                    }
                },
                {
                    "id": 20081,
                    "aisle": "Baking",
                    "image": "flour.png",
                    "consistency": "solid",
                    "name": "plain flour",
                    "original": "2 cups of plain flour",
                    "originalString": "2 cups of plain flour",
                    "originalName": "plain flour",
                    "amount": 2.0,
                    "unit": "cups",
                    "meta": [
                        "plain"
                    ],
                    "metaInformation": [
                        "plain"
                    ],
                    "measures": {
                        "us": {
                            "amount": 2.0,
                            "unitShort": "cups",
                            "unitLong": "cups"
                        },
                        "metric": {
                            "amount": 473.176,
                            "unitShort": "ml",
                            "unitLong": "milliliters"
                        }
                    }
                },
                {
                    "id": 2047,
                    "aisle": "Spices and Seasonings",
                    "image": "salt.jpg",
                    "consistency": "solid",
                    "name": "salt",
                    "original": "1/2 teaspoon salt",
                    "originalString": "1/2 teaspoon salt",
                    "originalName": "salt",
                    "amount": 0.5,
                    "unit": "teaspoon",
                    "meta": [],
                    "metaInformation": [],
                    "measures": {
                        "us": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons"
                        },
                        "metric": {
                            "amount": 0.5,
                            "unitShort": "tsps",
                            "unitLong": "teaspoons"
                        }
                    }
                },
                {
                    "id": 2050,
                    "aisle": "Baking",
                    "image": "vanilla-extract.jpg",
                    "consistency": "liquid",
                    "name": "vanilla extract",
                    "original": "3 tablespoon vanilla extract",
                    "originalString": "3 tablespoon vanilla extract",
                    "originalName": "vanilla extract",
                    "amount": 3.0,
                    "unit": "tablespoon",
                    "meta": [],
                    "metaInformation": [],
                    "measures": {
                        "us": {
                            "amount": 3.0,
                            "unitShort": "Tbsps",
                            "unitLong": "Tbsps"
                        },
                        "metric": {
                            "amount": 3.0,
                            "unitShort": "Tbsps",
                            "unitLong": "Tbsps"
                        }
                    }
                }
            ],
            "id": 716367,
            "title": "Vanilla Pound Cake",
            "readyInMinutes": 75,
            "servings": 10,
            "sourceUrl": "http://www.afrolems.com/2013/08/06/pound-cake-nigerian-cake/",
            "image": "https://spoonacular.com/recipeImages/716367-556x370.jpg",
            "imageType": "jpg",
            "summary": "Vanilla Pound Cake might be just the dessert you are searching for. This recipe serves 10 and costs 68 cents per serving. One serving contains <b>337 calories</b>, <b>6g of protein</b>, and <b>16g of fat</b>. A few people made this recipe, and 36 would say it hit the spot. If you have flour, salt, eggs, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>vegetarian</b> diet. From preparation to the plate, this recipe takes roughly <b>1 hour and 15 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 29%</b>. This score is not so super. Try <a href=\"https://spoonacular.com/recipes/vanilla-sour-cream-pound-cake-with-vanilla-glaze-66408\">Vanilla & Sour Cream Pound Cake With Vanilla Glaze</a>, <a href=\"https://spoonacular.com/recipes/lcd-vanilla-pound-cake-66385\">LCD” Vanilla Pound Cake</a>, and <a href=\"https://spoonacular.com/recipes/vanilla-pound-cake-913933\">Vanilla Pound Cake</a> for similar recipes.",
            "cuisines": [],
            "dishTypes": [
                "side dish"
            ],
            "diets": [
                "lacto ovo vegetarian"
            ],
            "occasions": [],
            "winePairing": {
                "pairedWines": [
                    "cream sherry",
                    "moscato dasti",
                    "port"
                ],
                "pairingText": "Dessert works really well with Cream Sherry, Moscato d'Asti, and Port. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. The NV Johnson Estate Cream Sherry with a 5 out of 5 star rating seems like a good match. It costs about 19 dollars per bottle.",
                "productMatches": [
                    {
                        "id": 430626,
                        "title": "NV Johnson Estate Cream Sherry",
                        "description": "Very aromatic with notes of hazelnut, vanilla, and a touch of oak followed by sweet raisins and a touch of yeast. Clean lasting finish. Good now but will reward those allow it to age\"\". A favorite pre-prandial beverage. Consider it with nuts before dinner as an aperitif, or after dinner with dessert, especially chocolates and fruit-based desserts. Also wonderful on cold afternoons, served with biscotti to dip in \"\"Italian-style\"\". \"",
                        "price": "$19.49",
                        "imageUrl": "https://spoonacular.com/productImages/430626-312x231.jpg",
                        "averageRating": 1.0,
                        "ratingCount": 2.0,
                        "score": 0.8571428571428572,
                        "link": "https://www.amazon.com/Johnson-Estate-Cream-Sherry-750/dp/B00D3GQSRW?tag=spoonacular-20"
                    }
                ]
            },
            "instructions": "<p><b><i>Step 1:</i></b> With the aid of a sifter, sift the dry ingredients (flour, baking powder, salt, nutmeg) into a bowl and set aside.<br><b><i>Step 2:</i></b> Grease the cake pan and dust with flour. Also pre-heat oven to 180 degrees Celsius<br><b><i>Step 3:</i></b> Put the butter, sugar and yogurt into a mixer or bowl {if you are using hand mixer}, mix until fluffy; mix on a high speed.<br><b><i>Step 4:</i></b> Crack in the eggs, one at a time…mix for about a minute before adding next. Then add the vanilla extract and mix.<br><b><i>Step 5:</i></b> Add the flour in batches; reduce the speed to the lowest and mixed. Once the flour is combined <b>(doesn’t have to be perfect)</b>, and then stop; so you don’t over work the batter.<br><b><i>Step 6:</i></b> At this point, add the milk and mix with a spatula until combined.<br><b><i>Step 7:</i></b> Pour batter into the greased cake pan and bake for approximately 50 minutes or until golden brown.</p>",
            "analyzedInstructions": [
                {
                    "name": "",
                    "steps": [
                        {
                            "number": 1,
                            "step": "With the aid of a sifter, sift the dry ingredients (flour, baking powder, salt, nutmeg) into a bowl and set aside.Step 2: Grease the cake pan and dust with flour. Also pre-heat oven to 180 degrees Celsius",
                            "ingredients": [
                                {
                                    "id": 2025,
                                    "name": "nutmeg",
                                    "localizedName": "nutmeg",
                                    "image": "ground-nutmeg.jpg"
                                },
                                {
                                    "id": 20081,
                                    "name": "all purpose flour",
                                    "localizedName": "all purpose flour",
                                    "image": "flour.png"
                                },
                                {
                                    "id": 2047,
                                    "name": "salt",
                                    "localizedName": "salt",
                                    "image": "salt.jpg"
                                }
                            ],
                            "equipment": [
                                {
                                    "id": 404747,
                                    "name": "cake form",
                                    "localizedName": "cake form",
                                    "image": "cake-pan.png"
                                },
                                {
                                    "id": 404708,
                                    "name": "sifter",
                                    "localizedName": "sifter",
                                    "image": "sifter.jpg"
                                },
                                {
                                    "id": 404783,
                                    "name": "bowl",
                                    "localizedName": "bowl",
                                    "image": "bowl.jpg"
                                },
                                {
                                    "id": 404784,
                                    "name": "oven",
                                    "localizedName": "oven",
                                    "image": "oven.jpg",
                                    "temperature": {
                                        "number": 180.0,
                                        "unit": "Celsius"
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "Put the butter, sugar and yogurt into a mixer or bowl {if you are using hand mixer}, mix until fluffy; mix on a high speed.Step 4 Crack in the eggs, one at a time…mix for about a minute before adding next. Then add the vanilla extract and mix.Step 5",
                    "steps": []
                },
                {
                    "name": "Add the flour in batches; reduce the speed to the lowest and mixed. Once the flour is combined (doesn’t have to be perfect), and then stop; so you don’t over work the batter.Step 6 At this point, add the milk and mix with a spatula until combined.Step 7",
                    "steps": [
                        {
                            "number": 1,
                            "step": "Pour batter into the greased cake pan and bake for approximately 50 minutes or until golden brown.",
                            "ingredients": [],
                            "equipment": [
                                {
                                    "id": 404784,
                                    "name": "oven",
                                    "localizedName": "oven",
                                    "image": "oven.jpg"
                                },
                                {
                                    "id": 404747,
                                    "name": "cake form",
                                    "localizedName": "cake form",
                                    "image": "cake-pan.png"
                                }
                            ],
                            "length": {
                                "number": 50,
                                "unit": "minutes"
                            }
                        }
                    ]
                }
            ],
            "originalId": null,
            "spoonacularSourceUrl": "https://spoonacular.com/vanilla-pound-cake-716367"
        }
    ]
}

**Comment by ghost** [comment]
https://api.spoonacular.com/recipes/random?apiKey=7d37456d810646b0bc25f4c4edc68b0c&tags=dinner, vegan
API request for random recipe

**Comment by ghost** [comment]
https://spoonacular.com/cdn/ingredients_100x100/tahini-paste.png
Get image for Ingredient

**Comment by ghost** [comment]
https://spoonacular.com/cdn/equipment_100x100/whisk.png
Get equipment for recipe
